version = "" # Bot version
env = "" # Current enviorment (test, dev, prod)
prefix = "" # Default command prefix
developer = "" # Developer user id
apiUrl = "" # kurozeropb.info api url

[tokens]
    dev = "" # Development bot token
    test = "" # Test bot token
    prod = "" # Production bot token
    error = "" # Webhook url for error handeling
    wolke = ""
    imdb = "" # Api key from omdb
    steam = "" # Steam api key
    kurozero = "" # Api auth token

    [tokens.botlists] # All the bot listing api keys
        BOTLIST_SPACE = ""
        BOTSFORDISCORD  = ""
        BOTS_ONDISCORD = ""
        DISCORDBOATS = ""
        DISCORDBOTS_ORG = ""
        DISCORDBOT_WORLD = ""
        DISCORD_BOTS_GG = ""
        DISCORDBOTS_GROUP = ""

[database]
    host = "" # MongoDB host
    port = 27017 # MongoDB port
    name = "" # MongoDB database name

[proxy]
    enabled = false # Enable or disable proxy usage for http requests
    host = "" # Proxy host
    port = 8080 # Proxy port
